### PR TITLE
Issue#60 add wikidata queries

### PR DESCRIPTION
**Pull request by MertCengiz**
All Wikidata Queries are found by semantic query analysis. Right now, this program is able to find all necessary information. However, integration with the back-end is essential

### CODE REVIEW

**Comment by sametaln** [comment]
Please update the base branch to the branch that you have created the `issue#60-add-wikidata-queries` from rather than main.

**Comment by sametaln** [comment]
The conflict is caused by the sparkqlwrapper requirement. Will the application work with `sparkqlwrapper` or do we need to use `SPARQLWrapper`? @MertCengiz

**Comment by MertCengiz** [comment]
`sparkqlwrapper` enables us to use SPARQL, which is essential to make searches. Without `sparkqlwrapper` , it is impossible to make semantic search. @sametaln

**Comment by MertCengiz** [comment]
Sorry for misunderstanding. There is no need for `sparqlwrapper` and `SPARQLWrapper` together in the requirements. Only `SPARQLWrapper` is sufficient. As we shouldn't merge this branch to the main, where should we merge; or, do we need to merge this branch at all right now? We have brances that already has improved featues right now. Thanks in advance @sametaln

**Comment by sametaln** [comment]
Are changes in this pr necessary for our backend? If not, we can delete and close this pull request.

**Pull request closed without merging**
