### PR TITLE
Reorganized files

### PR DESCRIPTION
**Pull request by oguzhekim**
Deleted views.py and serializers.py. Created new folders called views and serializers. Created new files inside these folders and copied contents of the views.py and serializers.py into these files. Please review the code and run the application. We need to make sure previous functionalities are preserved.

### CODE REVIEW

**Comment by sametaln** [comment]
Are we done with the restructuring?

**Comment by oguzhekim** [comment]
I tried backend part on my local and everything worked fine. But I need a review if everything works fine in dockerized version and functionalities are unharmed.

**Comment by sametaln** [comment]
I didn't mean that. Are you planning to do any other change on the backend?

**Comment by oguzhekim** [comment]
Not in this PR, no.

**Comment by sametaln** [comment]
Everything works fine. Thanks for the effor.

**Pull request closed without merging**
